CREATE TABLE tableName 
(
    create table articles (	VARCHAR(512),
    	VARCHAR(512)
);

INSERT INTO tableName (create table articles (, ) VALUES ('id serial primary key', '');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""articleId"" varchar  UNIQUE NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""userId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""vehicleId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""publicationDate"" bigint  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""brandId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""modelId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""generationId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""likes"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""comments"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""engine"" integer', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""wheeldrive"" integer', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""transmission"" integer', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""about"" integer[]        "', '');
INSERT INTO tableName (create table articles (, ) VALUES (')', '');
INSERT INTO tableName (create table articles (, ) VALUES ('', '');
INSERT INTO tableName (create table articles (, ) VALUES ('create table deleted_articles (', '');
INSERT INTO tableName (create table articles (, ) VALUES ('id serial primary key', '');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""articleId"" varchar  UNIQUE NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""userId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""vehicleId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""publicationDate"" bigint  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""brandId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""modelId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""generationId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""likes"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""comments"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""engine"" integer', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""wheeldrive"" integer', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""transmission"" integer', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""about"" integer[]', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""deletedDate"" bigint  NOT NULL"', '');
INSERT INTO tableName (create table articles (, ) VALUES (')', '');
INSERT INTO tableName (create table articles (, ) VALUES ('', '');
INSERT INTO tableName (create table articles (, ) VALUES ('', '');
INSERT INTO tableName (create table articles (, ) VALUES ('create table comments (', '');
INSERT INTO tableName (create table articles (, ) VALUES ('id serial primary key', '');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""articleId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""commentId"" varchar  UNIQUE NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""commentDate"" bigint  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""likes"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""answers"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""userId"" varchar  NOT NULL"', '');
INSERT INTO tableName (create table articles (, ) VALUES (')', '');
INSERT INTO tableName (create table articles (, ) VALUES ('', '');
INSERT INTO tableName (create table articles (, ) VALUES ('create table deleted_comments (', '');
INSERT INTO tableName (create table articles (, ) VALUES ('id serial primary key', '');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""articleId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""commentId"" varchar  UNIQUE NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""commentDate"" bigint  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""likes"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""answers"" integer  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""userId"" varchar  NOT NULL', '"');
INSERT INTO tableName (create table articles (, ) VALUES ('"        ""deletedDate"" bigint  NOT NULL"', '');
INSERT INTO tableName (create table articles (, ) VALUES (')', '');
